name: Sauce Labs Mobile Chrome Test

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:

  sauce-mobile-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mobile-tests

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"


    - name: Install dependencies
      run: |
        pip install -r mobile-tests/requirements.txt


    - name: Run Sauce Labs Test
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

      run: |
        pytest mobile-tests/tests
